spring:
  application:
    name: cibil-score-services
  config:
    import: configserver:http://localhost:8888
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: HR
    url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
    username: HR
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
